title: Hyas
titleSeparator: "-"
titleAddition: Modern Hugo Starter
description: >-
  Marie is a Hugo starter helping you build modern websites that are secure,
  fast, multi language and SEO-ready — by default.
images:
  - hyas.png
ogLocale: en_US
titleHome: Hyas Hugo Starter
twitterSite: "@gethyas"
twitterCreator: "@henkverlinde"
schemaType: Organization
schemaName: Hyas
schemaAuthor: Henk Verlinde
schemaAuthorTwitter: "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn: "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub: "https://github.com/h-enk"
schemaLocale: en-US
schemaLogo: logo-hyas.png
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: hyas.png
schemaImageWidth: 1280
schemaImageHeight: 640
schemaTwitter: "https://twitter.com/gethyas"
schemaLinkedIn: ""
schemaGitHub: "https://github.com/h-enk/hyas"
themeColor: "#fff"
quality: 85
bgColor: "#fff"
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: "300"
footer: >-
  Powered by <a href="https://www.netlify.com/">Netlify</a>, <a
  href="https://gohugo.io/">Hugo</a>, <a
  href="https://gethyas.com/">Hyas</a> and Love
copyRight: Copyright (c) 2020-2021 Henk Verlinde
alert: false
alertText: >-
  Deliver web projects 10x faster. <a class="alert-link"
  href="https://www.netlify.com/whitepaper/" target="_blank" rel="noopener">Get
  the free enterprise paper →</a>
